feat: root-to-minion replicator state syncronization
coherence/replication-server pull request #121
Opened 2020-08-25 12:43 UTC by kingstone426

Use the --parent-replicator parameter to specify a root replicator host address. 
Any state changes on the root replicator will be syncronized to the minion replicator.

2020-08-25 14:01 UTC, piot requested changes

2020-08-25 14:01 UTC, piot commented on src/server/server.go
> +		clog.Stringer("info", info), clog.String("connectionType", connectionType.String()))
we should use
```go
clog.Stringer("connectionType", connectionType)
```

2020-08-25 14:48 UTC, kingstone426 commented on src/server/connection_types.go
> +const Replicator ConnectionType = 0x02
Much nicer! I have updated the const declaration.

2020-08-25 14:49 UTC, kingstone426 commented on src/server/connection_types.go
> +	return fmt.Sprintf("invalid connection type %v", byte(ct))
Yes I agree. Updated implementation.

2020-08-25 14:50 UTC, kingstone426 commented on src/server/replicator_handlers.go
> +	worldPosition := ecs.ComponentTypeID(0)
Removed this code, it was just used for logging during development and shouldn't have made it into the PR.

2020-08-25 14:50 UTC, kingstone426 commented on src/server/server.go
> +		clog.Stringer("info", info), clog.String("connectionType", connectionType.String()))
Ahh so that's how Stringer is used! Nice

2020-08-25 14:51 UTC, kingstone426 commented on src/server/replicator_handlers.go
> +// ReplicatorMessageHandler ...
Added doc for the stub implementations.

2020-08-26 06:43 UTC, piot approved these changes

2020-08-26 06:43 UTC, piot commented on src/server/connection.go
> +		}
If we are only checking for an error, it is more nice to have them on one line. Also the `connectErr` variable is only scoped in the if statement. which is great.

```suggestion
		if connectErr := loadBalancer.OnSimulatorConnected(completeWorld.EntityManager(), c.participant, transferManager); connectErr != nil {
			return nil, connectErr
		}
```

2020-08-26 07:39 UTC, merged